### PR TITLE
Duck filled API

### PR DESCRIPTION
**Pull request by squirrelo**
This adds documentation and linting to the javascript, on top of the existing tests.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
We are good! We should probably squash all these commits.

**Comment by squirrelo** [comment]
I've squashed some of them. Should be good to go.

**Comment by ElDeveloper** [comment]
Did you forget to push? I still see > 80 commits, would be nice to have 1 or 2 at most, since these are all documentation additions, there's no point in keeping this history, and since you put the majority of work it would make sense for you to author the squashed commit.

**Comment by squirrelo** [comment]
Seems I'm having the sync-ing issue again. I'll try pushing again, but if that doesnt work I'll just close and open another PR.

**Pull request closed without merging**
