### PR TITLE
BUG: Fixed #370

### LINKED ISSUE #370: BUG: Taxa slider shows labels
Just realized that if the taxa slider is changed, the taxa labels will appear, even when the biplot visibility is disabled.

Give me a sec to fix this

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by emperor-helper** [comment]
The test build for this pull request can be found here: http://emperor.colorado.edu/pull_371/make_emperor/

**Comment by ElDeveloper** [comment]
It seems like the build timed out, I've restarted the build though.

**Comment by mortonjt** [comment]
Thanks!

**Comment by ElDeveloper** [comment]
Thanks @mortonjt

**Pull request merged**
