### PR TITLE
Very rough/incomplete code.

### PR DESCRIPTION
**Pull request by drhodges**

### CODE REVIEW

**Comment by emperor-helper** [comment]
The test build for this pull request can be found here: http://emperor.colorado.edu/pull_396/make_emperor/

**Comment by drhodges** [comment]
Candidate viewport example at: https://stemkoski.github.io/Three.js/Viewports-Quad.html

**Comment by josenavas** [comment]
@drhodges awesome!

**Comment by josenavas** [comment]
Merging to avoid some conflicts

**Pull request merged**
