### PR TITLE
Use require.js in the project

### PR DESCRIPTION
**Pull request by ElDeveloper**
We are now fully require.js compliant, I've updated the library code, the tests and the files under examples to use require.js. Consequently I've also added require.js to the project and to the licenses file.

Note that there are a lot of files being changed, but they all have very similar changes, essentially adding a couple lines where we specify the dependencies we want to import in that module, and then a line specifying the namespace these dependencies will use.

I had to do a fair amount of updates on the test suite, most notably, I had to introduce a couple of `asyncTest` as they were stochastically failing in the browser. I also noticed that we were misusing the `setup` and `teardown` methods, so I made a few changes to avoid using global variables.

Finally note that the indentation for almost all files that have been **require**-ified is a bit off i.e. most of the code should be indented a couple of spaces, but I decided that this is an easy thing to update once we have this first PR merged. Otherwise the diff would be too obnoxious to review.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
I need to update from #434 before this can be merged.

**Comment by ElDeveloper** [comment]
This should be ready for another review. A **very rough** demo of Emperor embedded in the notebook can be found [here](http://nbviewer.ipython.org/gist/ElDeveloper/57fe8feb11b46dc58add). Note that we still have some CSS leaks, and an image problem (checkmarks of the visibility tab won't appear on screen). I'll fix that in an upcoming PR i.e. when we introduce the proper Python API.

**Comment by wasade** [comment]
Should it be visible? I see the notebook but not the emperors... Although,
I'm on my phone right now

**Comment by antgonza** [comment]
I just tried on laptop and phone and they work fine. Not sure why doesn't show in @wasade's phone. Code looks fine. I think it will be OK to merge this and then fix all css in https://github.com/biocore/emperor/pull/435. @mortonjt, what do you think?

**Comment by wasade** [comment]
Probably internet connection... on ghetto roaming with my phone

**Comment by wasade** [comment]
:+1: on merge. @eldeveloper, do you want to create an issue about the
missing images?

**Comment by antgonza** [comment]
I'm gonna merge, added the image issue in https://github.com/biocore/emperor/pull/435 list.

**Comment by ElDeveloper** [comment]
Awesome, thanks a bunch guys! @wasade, I think the reason why that may
have happened, is because of require.js' async nature.

**Pull request merged**
