### PR TITLE
MAINT: Fix examples

### PR DESCRIPTION
**Pull request by ElDeveloper**
Since we added the SVGRenderer as a dependency the main config broke,
this should fix it.

### CODE REVIEW

**Comment by mortonjt** [comment]
👍 once the tests pass

**Comment by mortonjt** [comment]
Although, I'm noticing that there is the big Emperor logo in the middle of the screen when I open this up in the notebook ...  Should we raise an issue for this?

**Comment by mortonjt** [comment]
screen shot 2016-10-05 at 6 36 41 pm

**Comment by ElDeveloper** [comment]
Thanks for the screenshot, that's super strange. I had never seen that, can you try loading the same plot in another tab?

**Comment by mortonjt** [comment]
Found the problem on my end - it was pulling from an old version.

👍 @antgonza want to double check?

**Comment by ElDeveloper** [comment]
thanks 👏

**Pull request merged**
