### PR TITLE
DEV: Committing ipython display

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by emperor-helper** [comment]
The test build for this pull request can be found here: http://emperor.colorado.edu/pull_400/make_emperor/

**Comment by wasade** [comment]
Can't comment inline from phone but colorado. edu is mentioned as the
resources url

**Comment by mortonjt** [comment]
Hey @wasade. You are completely correct.  We are whipping up a demonstration for the hackathon on a separate developement branch.  These change will be definitely fixed once we start merging these changes on master

**Comment by wasade** [comment]
Ahh, sounds good :) explains all the commenting stuff too

**Comment by ElDeveloper** [comment]
Included in #401

**Pull request closed without merging**
