### PR TITLE
Improve error message for erroneous biplot_fp case

### PR DESCRIPTION
**Pull request by adamrp**
@wdwvt1 ran into this issue, and the error message was not clear enough to diagnose easily.

### CODE REVIEW

**Comment by antgonza** [comment]
Thanks, should taxa_fp have the same conditionals?

**Comment by adamrp** [comment]
Ideally, the code in cli for checking the `new_filepath` option type:
```python
def check_new_filepath(option, opt, value):
    return value
```
would be better, but that won't happen :laughing:

I theoretically could add the same checks for the 4 input and output files (-m, --biplot_fp, -s, taxa_fp), but I think that the cause for confusion for most people is about whether *outputs* are files/directories, and there is less confusion about the inputs. Opinions? @ElDeveloper @wdwvt1

**Comment by mortonjt** [comment]
:+1: for placing the error message into a function.  It'll prevent a bit of copying/pasting

**Comment by ElDeveloper** [comment]
I think we should avoid any work that gets into "patching" qcli, so I'm
fine with the solution in place. Is the error better now @wdwvt1?

**Comment by wdwvt1** [comment]
looks good to me!

**Comment by antgonza** [comment]
I think the solution is to remove qcli and use click, right? I think a semi-patch is worst than no-patch ...

**Comment by ElDeveloper** [comment]
Although I agree with that, I don't think we are going to be able to
port everything to click and keep backwards compatibility before
releasing anything else in the 0.9.x series, which we should do sometime
soon (lots of bugfixes we haven't released). I am hoping that after
0.9.6 we will go onto 1.0 and aggressively modify the CLI, replacing
qcli with click however QIIME users of the 1.9.x series won't have
access to that, thus it makes sense for this patch to exist.

**Comment by antgonza** [comment]
What about leaving the bug open and fix during click transition? I really don't like semi-patches ...

**Comment by antgonza** [comment]
Sorry for multiple messages. Note that my vote is to fully fix ...

**Comment by ElDeveloper** [comment]
But -s is the only file that is individually written out by
make_emperor.py right? Not sure what else would need to be changed.

**Comment by antgonza** [comment]
Good point, I got confused with `if biplot_fp and taxa_fp:` ... then I guess is a complete patch?

**Comment by ElDeveloper** [comment]
Ok, so we are all :+1: on this correct?

**Comment by antgonza** [comment]
OK with me.

**Comment by ElDeveloper** [comment]
Thanks @adamrp

**Pull request merged**
