### PR TITLE
BUG: Fix incorrect indices in --biplot_fp output

### LINKED ISSUE #389: biplots: output of --biplot_fp starts with pc0 not pc1
The output from --biplot_fp lists the first principal coordinate (in 2nd cell of row 1) as "pc0" when it should be "pc1".

### PR DESCRIPTION
**Pull request by ElDeveloper**
In addition to fixing the bug in #389, I've also removed a few strings
that were not being used anywhere.

Fixes #389

### CODE REVIEW

**Comment by emperor-helper** [comment]
The test build for this pull request can be found here: http://emperor.colorado.edu/pull_391/make_emperor/

**Comment by antgonza** [comment]
Real errors ...

**Comment by ElDeveloper** [comment]
Got 'em, thanks!

**Comment by mortonjt** [comment]
Looks good!  Shall I merge?

**Comment by ElDeveloper** [comment]
If you think it's good to go, sure!

**Pull request merged**
