### PR TITLE
PEP8 sort.py and test_sort.py

### PR DESCRIPTION
**Pull request by josenavas**
Partially #342

### CODE REVIEW

**Comment by emperor-helper** [comment]
The test build for this pull request can be found here: http://emperor.colorado.edu/pull_375/make_emperor/

**Comment by ElDeveloper** [comment]
:+1:

**Comment by mortonjt** [comment]
:+1: on the numpy docs!

**Comment by ElDeveloper** [comment]
Thanks @josenavas

**Pull request merged**
