### PR TITLE
TST: fix wording for one of the naturalSort tests

### PR DESCRIPTION
**Pull request by fedarko**
Just a small thing I noticed while working on https://github.com/biocore/empress/pull/159. Two of the `naturalSort` tests have the same title -- the second one's is inaccurate. This fixes that problem.

### CODE REVIEW

**Comment by fedarko** [comment]
Yeah, it looks like the [build is failing](https://travis-ci.com/github/fedarko/emperor/builds/163317003?utm_medium=notification&utm_source=email)...? I'm not sure what's going on.

**Comment by fedarko** [comment]
Ok, I think I figured it out -- my fork's `master` branch is out of date, so it doesn't have the latest commits. I'll merge that stuff in to my fork locally and then push it up, and then the diff should really just be one line with no conflicts this time.

**Comment by fedarko** [comment]
Alright, should be fixed now. Sorry for the confusion!!!

**Comment by ElDeveloper** [comment]
Thanks @fedarko

**Pull request merged**
