### PR TITLE
New JavaScript API

### LINKED ISSUE #128: Allow user to change the shape of the samples
Allow the user to select the shape of the samples based on metadata, the default will still be a sphere but we can add: cube, star, etc.

### PR DESCRIPTION
**Pull request by ElDeveloper**
The goal of this branch (`new-api`), is to add the core JavaScript objects and basic functionality needed to simultaneously create 2D, 3D and parallel plots using Emperor. These efforts are focused on enhancing the modularity and usability of the objects, allowing developers to quickly build on top of this existing framework whenever a new use-case becomes available.

For now we will be working against a branch called new-api, it will not yet be merged into master and it will have small and atomic pull requests (except for the initial one). This branch will not break backwards compatibility in the Python/CLI interface, and is planned to be released as part of the 0.9.6 series so we can test and debug before releasing 1.0.

For reviewers, note that these changes will not be immediately integrated into the main GUI code, since the idea is to get rid of most of the code in `emperor.js`.

In general the plan is as follows:
- [x] Clean up the code that we worked through at the BD2K hackathon, with the objective of removing any modifications made to the Python codebase.
  Add a new examples folder where simple JavaScript-built examples are showcased.
- [x] Create a minimal example where we can visualize and re-color a 3D scatter plot. Here the focus will be to test that a large number of values can be displayed on screen without choking the browser (see #178, #192).
- [x] Sketch out and implement the interface between the view controllers and the application controller.
- [x] Update JavaScript libraries where needed (THREE.js, jQuery, underscore, etc) (#362).
- Add the required controllers to interact with other aspects of the plot like opacity, scaling, shape, visible dimensions, etc.
  - [x] Improve on `ColorViewController` (see #440, #311) @squirrelo .
  - [x] Create `ScaleViewController` (remember to add #203) @squirrelo .
  - [x] Create `ShapeViewController` (would fix #128). @squirrelo.
  - [x] Create `AxesViewController`, think about whether this should be its own tab or if it should be a menu somewhere else (remember to consider #276, #248, #88, #326). @ElDeveloper 
  - [x] Create `AnimationsViewController` (remember to consider #421).
  - [x] Add splash screen to `EmperorController` (showing an emperor logo while the application loads). @squirrelo
- [x] Python API.
- [x] Python 3 ( #313 ).
- [x] Move make_emperor.py to click and document the click commands in RST like we used to have `make_emperor.py` (#313). This is addressed by QIIME2, see [this plugin](https://github.com/eldeveloper/q2-emperor).
- [x] Extend usability of 3D plots (#327). @squirrelo
- [x] Create a 2D plot (#303) .
- [x] Create create jackknifed plots
- [x] Create procrustes plots
- [x] Create vector plots
- [x] Create biplots (#326, #59, #193 & #87 ), remember to consider #75, #61 and #87.
- [x] Design and implement the controllers to dynamically create independent views into the same dataset. In other words, allow the user to visualize multiple Emperor plots in the same GUI.  For example using multiple 2D/3D plots that presents the same data colored in a different way and viewing different dimensions (not just the first three principal coordinates).

While there are other features that will soon be added, we need to at least have the changes described above in place before moving forward in other directions.

---

If you are curious our slides for the BD2K presentation can be found [here](https://docs.google.com/presentation/d/1ylRD5B4mpCYIFwNjT7ZC2oIsGlniVlxSpSIW3ydcheQ/edit?usp=sharing).

### CODE REVIEW

**Comment by emperor-helper** [comment]
The test build for this pull request can be found here: http://emperor.microbio.me/pull_405/make_emperor/

**Comment by josenavas** [comment]
Thanks for starting this @ElDeveloper 
excited to start moving forward for the rise of the new emperor!

**Comment by mortonjt** [comment]
It looks good!  Thanks @ElDeveloper !

**Comment by mortonjt** [comment]
Thanks @ElDeveloper , @josenavas for putting this together!

Do you guys think it would be worth while to add additional tests for multiple viewports within Penguin McHelper?  Or should that be a future PR?

**Comment by mortonjt** [comment]
Btw.  Looks like there is a weird error in travis concerning the virtualenv

**Comment by ElDeveloper** [comment]
That should be a future PR for sure.

**Comment by antgonza** [comment]
Note the coverage dropping ...

**Comment by ElDeveloper** [comment]
Yes, I think this is due to the removal of some of our own code, and the
fact that some of the qiime_backports are not super well tested.

**Comment by ElDeveloper** [comment]
It took a while, but I think it is now time to merge this really large branch. There's many more merge conflicts than what a human can resolve (I'll need to investigate what to do about that). Once we resolve this, I'll put together a release candidate for the official version 1.0.0

**Comment by antgonza** [comment]
😮

**Pull request closed without merging**
