### PR TITLE
implemented new form of animation where samples are only shown at a particular point in time without being traced by lines

### PR DESCRIPTION
**Pull request by ConstantinoSchillebeeckx**
Fix for https://github.com/biocore/emperor/issues/421

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Thanks for submitting this @ConstantinoSchillebeeckx! It seems like the tests are failing, did these work in your system? You can check this by running `./tests/all_tests.py`, if you want to run the javascript tests, you will need to have `phantomjs` installed.

Additionally, it seems like there's some tests missing for the js code being added. I also noticed there's a mix of tabs and spaces in the JS code, so I would try to homogenize this and get it to be the same as the surrounding code (which should be 2 spaces for all the JS, but there may be some exceptions).

Let me know if you need any help.

**Comment by ConstantinoSchillebeeckx** [comment]
This is my first time submitting some sort of pull-request and wasn't aware of the tests to be run.  I've run them on my end and some do, indeed fail.  I'm afraid I'm unsure why they fail as I'm unsure how they work.  I'm going to need some guidance on this ...

**Comment by ElDeveloper** [comment]
The tests being executed are all found under the `tests` folder in the base directory. So have a look at those, specifically, I think the culprits are `test_format.py`. and `test_core.py` (those are related to your changes AFAIK). For more information have a look at the [contributing guidelines](https://github.com/biocore/emperor/blob/master/CONTRIBUTING.md).

On the JavaScript side of things, it seems like there's a few things failing, you can either open `tests/javascript_tests/index.html` in your browser (there are two tests that fail in some browsers, these are found in the `test_ui.js` but you shouldn't worry about that as those pass just fine with phantom.js in our CI server), this should help you figure out what other things are failing.

Finally, it seems that you have changed a lot of tabs and spaces in code that you are not modifying, I would suggest to revert this change, and only limit the modifications to the changes you are proposing. This will help reviewing and maintaining the code.

**Comment by ConstantinoSchillebeeckx** [comment]
Just wanted to drop a note that these unit tests, formatting and git branching is all above my head - I'm therefore giving up on it.

For those interested, a saved version of the modified animation format can be found [here](https://drive.google.com/file/d/0B4Ou4lclm6GQcHRFZXFFSmsyekk/view?usp=sharing).

**Pull request closed without merging**
