### PR TITLE
PRE-REL: Pre-release for QIIME2 workshop

### PR DESCRIPTION
**Pull request by ElDeveloper**

### CODE REVIEW

**Comment by antgonza** [comment]
👍 , I think 1 reviewer is fine, right?

**Comment by mortonjt** [comment]
👍 now you have 2 :)

**Comment by ElDeveloper** [comment]
🎉

**Comment by ElDeveloper** [comment]
Thanks @antgonza & @mortonjt, can someone merge this?

**Comment by ElDeveloper** [comment]
Thanks!

**Pull request merged**
