### PR TITLE
BUG: Fix problem with icons not showing in the nb

### PR DESCRIPTION
**Pull request by ElDeveloper**
Replace the images used by SlickGrid to be jQuery icons.

Fixes a point in #435

### CODE REVIEW

**Comment by ElDeveloper** [comment]
This won't show in the source code, but I replaced this:
```html
<img src='../emperor/support_files/vendor/js/images/tick.png'>
```

For this:
```html
<div class='ui-state-default ui-corner-all'>
     <span class='ui-icon ui-icon-check'>
</span></div>
```

Which results in this:

screen shot 2016-04-27 at 12 09 37 pm

As you can see we now have crosses and ticks for the visibility tab.

**Comment by ElDeveloper** [comment]
Do not merge, I just found a problem!

**Comment by ElDeveloper** [comment]
Nix that, I wasn't able to reproduce the problem.  `¯\_(ツ)_/¯`, just for the record, if someone sees a horizontal scroll bar in one of the view controllers, let me know, that's the problem I saw for a second, and then I wasn't able to see or reproduce again.

**Comment by squirrelo** [comment]
👍

**Comment by ElDeveloper** [comment]
If this looks good can someone merge this?

**Pull request merged**
