### PR TITLE
Improve functionality discoverability

### PR DESCRIPTION
**Pull request by ElDeveloper**
This PR adds tooltips to lots of UI elements:

- Attribute editors in every tab now change mouse type when the mouse hovers over.
- Editors are now activated with one click (I've left out the updates for the scale in visibility in #596).
- The scree plot now shows a tooltip with the percent explained value.
- Tabs display help text when hovering over them.

This GIF tries to showcase most of these:

tooltips

Related to #586.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
This is ready for review/merge.

**Comment by ElDeveloper** [comment]
@josenavas, thanks for reviewing! One reviewer should be fine 😃

**Comment by josenavas** [comment]
Cheers then 🍻

**Comment by ElDeveloper** [comment]
Thanks!

**Pull request merged**
